### ISSUE TITLE
Updates to the CMBenv environment

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast-workshop-ucsd-2019#12]
@tskisner It would be useful to have `nbstripout` in the Jupyter environment so we can perform that operation at NERSC

**Comment by zonca** [comment]
can you please also install `black`?

**Comment by zonca** [comment]
also `healpy 1.12.9` -> `1.12.10` should get rid of the ugly warning when plotting

**Comment by tskisner** [comment]
Ok, I had already added nbstripout:

https://github.com/hpc4cmb/cmbenv/blob/master/pkgs/python.sh#L79

And had already added slurm-magic:

https://github.com/hpc4cmb/cmbenv/blob/master/pkgs/slurmmagic.sh

I'll update healpy and add black to the package list.

**Comment by zonca** [comment]
thanks, please let me know when you have a new kernel so I can re-test my lesson

**Comment by tskisner** [comment]
Sorry, I replied in the other PR thread.  The new kernel (20191012) was installed late last night.

**Comment by zonca** [comment]
ok
