### ISSUE TITLE
TOC autonumbering

### ISSUE THREAD

**Issue by zonca** [hpc4cmb/toast-workshop-ucsd-2019#14]
@tskisner @keskitalo Just noticed that JupyterLab can auto-number the sections,
I think that is nice for attendees that get lost during a lesson.

Once it is activated, it is saved in the ipynb metadata.

To activate, there is button in the TOC:

![image](https://user-images.githubusercontent.com/383090/66709253-2d342900-ed15-11e9-8b15-20be51afa4f3.png)

**Comment by keskitalo** [comment]
I don't see a TOC anywhere in my jupyterlab window.

**Comment by tskisner** [comment]
It's on the very left side bar of the NERSC jupyter lab (see Andrea's screen shot) you can switch between the TOC and the file browser view.

**Comment by keskitalo** [comment]
Thanks. It is not available in my install of jupyterlab. I'll enable at NERSC.

**Comment by keskitalo** [comment]
I found the extension at https://github.com/jupyterlab/jupyterlab-toc and installed it on my laptop. I presume enabling the extension in the notebooks will not render them unusable to folks who do not have the extension installed.

The TOC is a great addition!

**Comment by zonca** [comment]
Very good
