### ISSUE TITLE
Tracking software version without kernel version

### ISSUE THREAD

**Issue by tskisner** [hpc4cmb/toast-workshop-ucsd-2019#9]
Having merged #8, I am having second thoughts.  Consider this:  what we mostly care about is not the kernel that is currently used for a notebook, but rather the version of toast that is used by that kernel.  Hardcoding the kernel version is a pain when running notebooks in different places (laptop, NERSC, SDSC, etc).  Here is one proposal for consideration:

1.  Strip out the kernel version on commit.
2.  Add a function to the common tools that checks the toast version and determines if is sufficient

This would allow people to run their own kernels, but also make sure that we are running with a version of toast that behaves in the way we expect.

@zonca and others, any thoughts on this idea?

**Comment by zonca** [comment]
I agree with this

**Comment by zonca** [comment]
Keep this open, but let's do the notebooks first

**Comment by tskisner** [comment]
Sounds good.

**Comment by zonca** [comment]
it would be nice if `cmbenv-jupyter` printed out what version of kernel it created
